#!/usr/bin/env python3

import toml
import json
import sys


def main():
    with open(sys.argv[1], 'r') as f:
        data = toml.load(f)
    print(json.dumps(data, indent=2))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f'Usage: {sys.argv[0]} toml-file')
    else:
        main()
